const data = [
  {
    id: 519,
    title: "Space Punks",
    thumbnail: "https://www.freetogame.com/g/519/thumbnail.jpg",
    short_description:
      "Space Punks is a sci-fi co-op looter shooter with graphics and humor that will likely appeal to the Borderlands fans among us.",
    game_url: "https://www.freetogame.com/open/space-punks",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "JAGEX",
    developer: "Flying Wild Hog",
    release_date: "2022-04-20",
    freetogame_profile_url: "https://www.freetogame.com/space-punks",
  },
  {
    id: 516,
    title: "PUBG: BATTLEGROUNDS",
    thumbnail: "https://www.freetogame.com/g/516/thumbnail.jpg",
    short_description:
      "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
    game_url: "https://www.freetogame.com/open/pubg",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "KRAFTON, Inc.",
    developer: "KRAFTON, Inc.",
    release_date: "2022-01-12",
    freetogame_profile_url: "https://www.freetogame.com/pubg",
  },
  {
    id: 515,
    title: "Halo Infinite",
    thumbnail: "https://www.freetogame.com/g/515/thumbnail.jpg",
    short_description:
      "For the first time ever, a free-to-play Halo experience is available in the form of Halo Infinite’s multiplayer.",
    game_url: "https://www.freetogame.com/open/halo-infinite",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Xbox Game Studios",
    developer: "343 Industries",
    release_date: "2021-11-15",
    freetogame_profile_url: "https://www.freetogame.com/halo-infinite",
  },
  {
    id: 514,
    title: "Skydome",
    thumbnail: "https://www.freetogame.com/g/514/thumbnail.jpg",
    short_description:
      "Take a 4v4 tower defense game, add a touch of MOBA, and you have gamigo and Kinship Game Studio’s Skydome.",
    game_url: "https://www.freetogame.com/open/skydome",
    genre: "Moba",
    platform: "PC (Windows)",
    publisher: "gamigo US Inc.",
    developer: "Kinship Game Studio Ltda",
    release_date: "2021-08-18",
    freetogame_profile_url: "https://www.freetogame.com/skydome",
  },
  {
    id: 518,
    title: "Swords of Legends Online",
    thumbnail: "https://www.freetogame.com/g/518/thumbnail.jpg",
    short_description:
      "Explore a fantasy world based on Chinese mythology in Gameforge’s action MMORPG Swords of Legends Online!",
    game_url: "https://www.freetogame.com/open/swords-of-legends-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Gameforge",
    developer: "Wangyuan Shengtang Entertainment",
    release_date: "2021-07-09",
    freetogame_profile_url:
      "https://www.freetogame.com/swords-of-legends-online",
  },
  {
    id: 513,
    title: "Super Squad",
    thumbnail: "https://www.freetogame.com/g/513/thumbnail.jpg",
    short_description:
      "Prepare yourself. It’s time for Mayhem. Super Squad is a multi-player online shoot-’em-up (or MOSH)!",
    game_url: "https://www.freetogame.com/open/super-squad",
    genre: "Moba",
    platform: "PC (Windows)",
    publisher: "Bad Fox Studios",
    developer: "Bad Fox Studios",
    release_date: "2021-06-25",
    freetogame_profile_url: "https://www.freetogame.com/super-squad",
  },
  {
    id: 511,
    title: "Phantasy Star Online 2 New Genesis",
    thumbnail: "https://www.freetogame.com/g/511/thumbnail.jpg",
    short_description:
      "The legacy of Phantasy Star Online 2 continues a thousand years later!",
    game_url: "https://www.freetogame.com/open/pso2-new-genesis",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Sega",
    developer: "Sega",
    release_date: "2021-06-09",
    freetogame_profile_url: "https://www.freetogame.com/pso2-new-genesis",
  },
  {
    id: 512,
    title: "Sherwood Extreme",
    thumbnail: "https://www.freetogame.com/g/512/thumbnail.jpg",
    short_description:
      "High action arcade shooter Sherwood Extreme sends players on a mission to save the kingdom!",
    game_url: "https://www.freetogame.com/open/sherwood-extreme",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "CAGE Studios",
    developer: "CAGE Studios",
    release_date: "2021-05-12",
    freetogame_profile_url: "https://www.freetogame.com/sherwood-extreme",
  },
  {
    id: 510,
    title: "Drifters Loot the Galaxy",
    thumbnail: "https://www.freetogame.com/g/510/thumbnail.jpg",
    short_description:
      "Grab your Driftpacs and grappling hooks, it’s time to loot. Pick a character and dive into Blind Squirrel’s team-based shooter, Drifters Loot the Galaxy.",
    game_url: "https://www.freetogame.com/open/drifters-loot-the-galaxy",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Blind Squirrel Entertainment",
    developer: "Blind Squirrel Entertainment",
    release_date: "2021-04-15",
    freetogame_profile_url:
      "https://www.freetogame.com/drifters-loot-the-galaxy",
  },
  {
    id: 509,
    title: "Smash Legends",
    thumbnail: "https://www.freetogame.com/g/509/thumbnail.jpg",
    short_description:
      "Classic fairy tales get wild with 5minlab and LINE Games Corporation’s brawl-action game Smash Legends.",
    game_url: "https://www.freetogame.com/open/smash-legends",
    genre: "Fighting",
    platform: "PC (Windows)",
    publisher: "LINE Games Corporation",
    developer: "5minlab",
    release_date: "2021-04-13",
    freetogame_profile_url: "https://www.freetogame.com/smash-legends",
  },
  {
    id: 508,
    title: "Enlisted",
    thumbnail: "https://www.freetogame.com/g/508/thumbnail.jpg",
    short_description:
      "Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ",
    game_url: "https://www.freetogame.com/open/enlisted",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Gaijin Entertainment",
    developer: "Darkflow Software",
    release_date: "2021-04-08",
    freetogame_profile_url: "https://www.freetogame.com/enlisted",
  },
  {
    id: 507,
    title: "Super Mecha Champions",
    thumbnail: "https://www.freetogame.com/g/507/thumbnail.jpg",
    short_description:
      "Super Mecha Champions is a PC port of the mobile anime PvP game from NetEease, featuring a variety of modes but focusing on battle royale.",
    game_url: "https://www.freetogame.com/open/super-mecha-champions",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "NetEase Games",
    developer: "NetEase Games",
    release_date: "2021-03-25",
    freetogame_profile_url: "https://www.freetogame.com/super-mecha-champions",
  },
  {
    id: 502,
    title: "Primordials: Battle of Gods",
    thumbnail: "https://www.freetogame.com/g/502/thumbnail.jpg",
    short_description:
      "Build armies and fight for control of the realm in Global Dodo Entertainment’s 1v1 strategy game Primordials: Battle of Gods. ",
    game_url: "https://www.freetogame.com/open/primordials-battle-of-gods",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Wire Games",
    developer: "Global Dodo Entertainment",
    release_date: "2021-03-04",
    freetogame_profile_url:
      "https://www.freetogame.com/primordials-battle-of-gods",
  },
  {
    id: 500,
    title: "Chroma: Bloom And Blight",
    thumbnail: "https://www.freetogame.com/g/500/thumbnail.jpg",
    short_description:
      "Competitive card game fans have a new, completely free option to add to their list. ",
    game_url: "https://www.freetogame.com/open/chroma-bloom-and-blight",
    genre: "Card",
    platform: "PC (Windows)",
    publisher: "WhisperGames",
    developer: "Clarity Games",
    release_date: "2021-01-28",
    freetogame_profile_url:
      "https://www.freetogame.com/chroma-bloom-and-blight",
  },
  {
    id: 497,
    title: "Astellia Royal",
    thumbnail: "https://www.freetogame.com/g/497/thumbnail.jpg",
    short_description:
      "Gamers interested in Studio8’s MMO Astellia now have a new – and slightly different – free-to-play option, Astellia Royal",
    game_url: "https://www.freetogame.com/open/astellia-royal",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Way2Bit",
    developer: "Studio 8",
    release_date: "2020-12-12",
    freetogame_profile_url: "https://www.freetogame.com/astellia-royal",
  },
  {
    id: 498,
    title: "Blankos Block Party",
    thumbnail: "https://www.freetogame.com/g/498/thumbnail.jpg",
    short_description:
      "What happens when you take the vinyl collectible toy experience and combine it with an open-world multiplayer game? You get Blankos Block Party!\r\n",
    game_url: "https://www.freetogame.com/open/blankos",
    genre: "MMO",
    platform: "PC (Windows)",
    publisher: "Third Kind Games",
    developer: "Mythical Games Inc",
    release_date: "2020-12-11",
    freetogame_profile_url: "https://www.freetogame.com/blankos",
  },
  {
    id: 499,
    title: "Slapshot: Rebound",
    thumbnail: "https://www.freetogame.com/g/499/thumbnail.jpg",
    short_description:
      "Do you like hockey? How about physic-based multiplayer, arcade-style sports games with cute graphics? Well, this is the one for you.",
    game_url: "https://www.freetogame.com/open/slapshot-rebound",
    genre: "Sports",
    platform: "PC (Windows)",
    publisher: "Oddshot Games",
    developer: "Oddshot Games",
    release_date: "2020-12-07",
    freetogame_profile_url: "https://www.freetogame.com/slapshot-rebound",
  },
  {
    id: 479,
    title: "Blood of Steel",
    thumbnail: "https://www.freetogame.com/g/479/thumbnail.jpg",
    short_description:
      "Blood of Steel is an online competitive strategy game featuring some of the most well-known figures throughout medieval history. Choose your general – a Crusader, Viking, Ninja or one of those from the Three Kingdoms. Build your kingdom and command armies in epic PvP battles using classic medieval warfare tactics.",
    game_url: "https://www.freetogame.com/open/blood-of-steel",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "YC Games",
    developer: "YC Games",
    release_date: "2020-10-20",
    freetogame_profile_url: "https://www.freetogame.com/blood-of-steel",
  },
  {
    id: 477,
    title: "Eternal Return: Black Survival",
    thumbnail: "https://www.freetogame.com/g/477/thumbnail.jpg",
    short_description:
      "Combining elements from battle royale, MOBA, and the survival genres, Eternal Return: Black Survival is a game designed with a broad audience in mind. ",
    game_url: "https://www.freetogame.com/open/eternal-return",
    genre: "MOBA",
    platform: "PC (Windows)",
    publisher: "Nimble Neuron",
    developer: "Nimble Neuron",
    release_date: "2020-10-14",
    freetogame_profile_url: "https://www.freetogame.com/eternal-return",
  },
  {
    id: 476,
    title: "Rogue Company",
    thumbnail: "https://www.freetogame.com/g/476/thumbnail.jpg",
    short_description:
      "From Hi-Rez Studios, the team that brought you Smite and Paladins, comes Rogue Company, a cross-platform, competitive team-based third person shooter.",
    game_url: "https://www.freetogame.com/open/rogue-company",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Nexon",
    developer: "Valofe",
    release_date: "2020-10-01",
    freetogame_profile_url: "https://www.freetogame.com/rogue-company",
  },
  {
    id: 475,
    title: "Genshin Impact",
    thumbnail: "https://www.freetogame.com/g/475/thumbnail.jpg",
    short_description:
      "If you’ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you’re going to want to check out miHoYo’s Genshin Impact.",
    game_url: "https://www.freetogame.com/open/genshin-impact",
    genre: "Action RPG",
    platform: "PC (Windows)",
    publisher: "miHoYo",
    developer: "miHoYo",
    release_date: "2020-09-28",
    freetogame_profile_url: "https://www.freetogame.com/genshin-impact",
  },
  {
    id: 474,
    title: "Rocket League",
    thumbnail: "https://www.freetogame.com/g/474/thumbnail.jpg",
    short_description:
      "Get your car-soccer gaming on for free with Psyonix’s Rocket League. The popular competitive multi-player game is a popular offering with over 57 million players.",
    game_url: "https://www.freetogame.com/open/rocket-league",
    genre: "Sports",
    platform: "PC (Windows)",
    publisher: "Psyonix LLC",
    developer: "Psyonix LLC",
    release_date: "2020-09-24",
    freetogame_profile_url: "https://www.freetogame.com/rocket-league",
  },
  {
    id: 473,
    title: "Spellbreak",
    thumbnail: "https://www.freetogame.com/g/473/thumbnail.jpg",
    short_description:
      "Spellbreak is a multiplayer, multi-platform battle-royale where player take on the role of a “battlemage” mastering elemental magic and using spells to compete against other players.",
    game_url: "https://www.freetogame.com/open/spellbreak",
    genre: "Battle Royale",
    platform: "PC (Windows)",
    publisher: "Proletariat",
    developer: "Proletariat",
    release_date: "2020-09-04",
    freetogame_profile_url: "https://www.freetogame.com/spellbreak",
  },
  {
    id: 471,
    title: "Armor Valor",
    thumbnail: "https://www.freetogame.com/g/471/thumbnail.jpg",
    short_description:
      "Build your empire with the help of mythical heroes and well thought out strategy in R2 Games’ strategy RPG Armor Valor.",
    game_url: "https://www.freetogame.com/open/armor-valor",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "R2 Games",
    release_date: "2020-07-20",
    freetogame_profile_url: "https://www.freetogame.com/armor-valor",
  },
];
